variables:
  - name: default_build_type
    default: null
    description: "Choose the default build type for the workspace. Options are 'Debug', 'RelWithDebInfo' and 'Release'."
    choices:
      - "Debug"
      - "RelWithDebInfo"
      - "Release"
      - "MinSizeRel"
      - "Default"
  - name: workspace_install
    default: "isolated"
    description: "Choose the install type for the workspace. Options are 'isolated', 'merged' and 'symlink'.\n\
      The ROS2 default is 'isolated' which installs all packages into their own subfolder in the install folder.\n\
      'merged' installs all packages into the same folder.\n\
      'symlink' creates symlinks to the source folder. This is useful for development and makes changes to urdf
      and python packages available without rebuild."
    choices:
      - "isolated"
      - "merged"
      - "symlink"